import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> sys_info: "Loading...";

    VerticalBox {
        alignment: center;
        Text {
            text: "Android System Info:";
            font-size: 24px;
            horizontal-alignment: center;
        }

        Text {
            text: root.sys_info;
            font-size: 18px;
            horizontal-alignment: center;
            color: #a0a0a0;
        }
    }
}
